#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status $against -- | grep -E '^[AUM].*\.md$'| cut -c3-`; do
  find $FILE | xargs sed -i "s/、/,/g"
  find $FILE | xargs sed -i "s/。/./g"
  git add $FILE
done
